on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk
      
    steps:
    - uses: actions/checkout@v3
    - run: make web
    - uses: actions/upload-artifact@master
      with:
        name: page
        path: web
        if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
      
    steps:
    - uses: actions/download-artifact@master
      with:
        name: page
        path: .
    - uses: actions/configure-pages@v1
    - uses: actions/upload-pages-artifact@v1
      with:
        path: .
    - id: deployment
      uses: actions/deploy-pages@main
